/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfas;

/**
 *
 * @author Frank
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipa = new javax.swing.JPanel();
        borrarTodo = new javax.swing.JButton();
        porcentaje = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        divisor = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        anterior = new javax.swing.JButton();
        coma = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Pantalla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(500, 600));

        PanelPrincipa.setBackground(new java.awt.Color(204, 204, 204));
        PanelPrincipa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        borrarTodo.setText("c");
        borrarTodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarTodoMouseClicked(evt);
            }
        });
        PanelPrincipa.add(borrarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 80, 70));

        porcentaje.setText("%");
        porcentaje.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                porcentajeMouseClicked(evt);
            }
        });
        PanelPrincipa.add(porcentaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 80, 70));

        jButton3.setText("                                      ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        PanelPrincipa.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 80, 70));

        tres.setText("3");
        tres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tresMouseClicked(evt);
            }
        });
        PanelPrincipa.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 80, 70));

        uno.setText("1");
        uno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unoMouseClicked(evt);
            }
        });
        PanelPrincipa.add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 80, 70));

        dos.setText("2");
        dos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dosMouseClicked(evt);
            }
        });
        PanelPrincipa.add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 80, 70));

        seis.setText("6");
        seis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seisMouseClicked(evt);
            }
        });
        PanelPrincipa.add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 80, 70));

        cuatro.setText("4");
        cuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuatroMouseClicked(evt);
            }
        });
        PanelPrincipa.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 80, 70));

        cinco.setText("5");
        cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cincoMouseClicked(evt);
            }
        });
        PanelPrincipa.add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 80, 70));

        nueve.setText("9");
        nueve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nueveMouseClicked(evt);
            }
        });
        PanelPrincipa.add(nueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 80, 70));

        siete.setText("7");
        siete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sieteMouseClicked(evt);
            }
        });
        PanelPrincipa.add(siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 80, 70));

        ocho.setText("8");
        ocho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ochoMouseClicked(evt);
            }
        });
        PanelPrincipa.add(ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 80, 70));

        borrar.setText("<--");
        borrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrarMouseClicked(evt);
            }
        });
        PanelPrincipa.add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 80, 70));

        divisor.setText("/");
        divisor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisorMouseClicked(evt);
            }
        });
        divisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisorActionPerformed(evt);
            }
        });
        PanelPrincipa.add(divisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 80, 70));

        resta.setText("-");
        resta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restaMouseClicked(evt);
            }
        });
        resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaActionPerformed(evt);
            }
        });
        PanelPrincipa.add(resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 80, 70));

        suma.setText("+");
        suma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumaMouseClicked(evt);
            }
        });
        PanelPrincipa.add(suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 80, 70));

        anterior.setText("  ANT   ");
        PanelPrincipa.add(anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 80, 70));

        coma.setText(",");
        coma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comaMouseClicked(evt);
            }
        });
        PanelPrincipa.add(coma, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 80, 70));

        cero.setText("0");
        cero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ceroMouseClicked(evt);
            }
        });
        PanelPrincipa.add(cero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 80, 70));

        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });
        PanelPrincipa.add(igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 80, 70));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pantalla, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        PanelPrincipa.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 350, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipa, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipa, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void divisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_divisorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_igualActionPerformed

    private void restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_restaActionPerformed

    private void porcentajeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_porcentajeMouseClicked
        Pantalla.setText(Pantalla.getText()+"%");
    }//GEN-LAST:event_porcentajeMouseClicked

    private void unoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unoMouseClicked
        Pantalla.setText(Pantalla.getText()+"1");
    }//GEN-LAST:event_unoMouseClicked

    private void dosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dosMouseClicked
        Pantalla.setText(Pantalla.getText()+"2");
    }//GEN-LAST:event_dosMouseClicked

    private void tresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tresMouseClicked
        Pantalla.setText(Pantalla.getText()+"3");
    }//GEN-LAST:event_tresMouseClicked

    private void cuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuatroMouseClicked
        Pantalla.setText(Pantalla.getText()+"4");
    }//GEN-LAST:event_cuatroMouseClicked

    private void cincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincoMouseClicked
        Pantalla.setText(Pantalla.getText()+"5");
    }//GEN-LAST:event_cincoMouseClicked

    private void seisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seisMouseClicked
        Pantalla.setText(Pantalla.getText()+"6");
    }//GEN-LAST:event_seisMouseClicked

    private void sieteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sieteMouseClicked
        Pantalla.setText(Pantalla.getText()+"7");
    }//GEN-LAST:event_sieteMouseClicked

    private void ochoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ochoMouseClicked
        Pantalla.setText(Pantalla.getText()+"8");
    }//GEN-LAST:event_ochoMouseClicked

    private void nueveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nueveMouseClicked
        Pantalla.setText(Pantalla.getText()+"9");
    }//GEN-LAST:event_nueveMouseClicked

    private void ceroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ceroMouseClicked
        Pantalla.setText(Pantalla.getText()+"0");
    }//GEN-LAST:event_ceroMouseClicked

    private void comaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comaMouseClicked
        Pantalla.setText(Pantalla.getText()+",");
    }//GEN-LAST:event_comaMouseClicked

    private void sumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumaMouseClicked
        Pantalla.setText(Pantalla.getText()+"+");
    }//GEN-LAST:event_sumaMouseClicked

    private void restaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaMouseClicked
        Pantalla.setText(Pantalla.getText()+"-");
    }//GEN-LAST:event_restaMouseClicked

    private void divisorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisorMouseClicked
        Pantalla.setText(Pantalla.getText()+"/");
    }//GEN-LAST:event_divisorMouseClicked

    private void borrarTodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarTodoMouseClicked
        Pantalla.setText("");
    }//GEN-LAST:event_borrarTodoMouseClicked

    private void borrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrarMouseClicked
        Pantalla.setText(Pantalla.getText().substring(0,Pantalla.getText().length()-1));
    }//GEN-LAST:event_borrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPrincipa;
    private javax.swing.JLabel Pantalla;
    private javax.swing.JButton anterior;
    private javax.swing.JButton borrar;
    private javax.swing.JButton borrarTodo;
    private javax.swing.JButton cero;
    private javax.swing.JButton cinco;
    private javax.swing.JButton coma;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton divisor;
    private javax.swing.JButton dos;
    private javax.swing.JButton igual;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JButton porcentaje;
    private javax.swing.JButton resta;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton suma;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration//GEN-END:variables
}
